### ISSUE TITLE
`minimum_password_strength()` function does not exist

### ISSUE THREAD

**Issue by tyrann0us** [CodeAwhile/minimum-password-strength#3]
Hi @ryanhellyer,
the following line fails with `Warning: call_user_func_array() expects parameter 1 to be a valid callback, function 'minimum_password_strength' not found or invalid function name in /path/to/wp/wp-includes/class-wp-hook.php on line 288`:

https://github.com/CodeAwhile/minimum-password-strength/blob/df3715d9936fcffa7412ebb23ba2d1e721ce445f/minimum-password-strength.php#L13

The function `minimum_password_strength()` indeed does not exist in this plugin or in WordPress.

**Comment by ryanhellyer** [comment]
But it's literally on the line below it. That's the only function in the plugin after the last commit that I added.

**Comment by tyrann0us** [comment]
I must have been mentally deranged when I read the code. And I have no idea why the error occurred.
